# Generated by Django 6.0.2 on 2026-02-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_mm_cd_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("source", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
                (
                    "agent_name",
                    models.CharField(blank=True, default="general", max_length=50),
                ),
                ("message", models.TextField()),
                ("action_taken", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileChangeAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("file_path", models.CharField(max_length=500)),
                ("change_type", models.CharField(max_length=20)),
                ("tier", models.IntegerField()),
                ("agent_name", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True, null=True)),
                ("diff_summary", models.TextField(blank=True, null=True)),
                (
                    "backup_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskOfficerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("cycle_number", models.IntegerField(blank=True, null=True)),
                ("review_json", models.TextField(default="")),
                ("portfolio_risk_summary", models.TextField(default="")),
                ("trades_reviewed", models.IntegerField(default=0)),
                ("trades_flagged", models.IntegerField(default=0)),
                ("trades_rejected", models.IntegerField(default=0)),
                (
                    "parameter_recommendations",
                    models.JSONField(blank=True, default=list),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StrategistAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("assessment_json", models.TextField(default="")),
                ("summary", models.TextField(default="")),
                ("market_regime", models.CharField(default="normal", max_length=20)),
                ("regime_confidence", models.FloatField(default=0.5)),
                ("allocation_score", models.IntegerField(blank=True, null=True)),
                ("diversification_score", models.IntegerField(blank=True, null=True)),
                ("category_allocation", models.JSONField(blank=True, default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("strategic_insights", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
